Ext.ns("PXDEBUG","PXDEBUG.app","PXDEBUG.grid","PXDEBUG.form","PXDEBUG.tree");if(!window.console)window.console={log:Ext.emptyFn,dir:Ext.emptyFn,debug:Ext.emptyFn,info:Ext.emptyFn,warn:Ext.emptyFn,error:Ext.emptyFn,time:Ext.emptyFn,timeEnd:Ext.emptyFn,pforile:Ext.emptyFn,pfofileEnd:Ext.emptyFn,trace:Ext.emptyFn,group:Ext.emptyFn,groupEnd:Ext.emptyFn,dirxml:Ext.emptyFn};
PXDEBUG.app.App=Ext.extend(Ext.util.Observable,{commonInit:function(){Ext.BLANK_IMAGE_URL=relpath+"extjs/resources/images/default/s.gif";Ext.QuickTips.init();Ext.Direct.addProvider(PXDEBUG.app.REMOTING_API);var a=Ext.maxZindex();if(Ext.WindowMgr.zseed<a)Ext.WindowMgr.zseed=a;Ext.apply(this,{showed:false,enable:true,keymaps:{},config:{css:{ExtJS_All_CSS:relpath+"extjs/resources/css/ext-all.css",ExtJS_All_CSS_THEME:relpath+"extjs/resources/css/xtheme-gray.css"}}});this.keymaps.query=new Ext.KeyMap(document,
{key:Ext.EventObject.Q,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("query")},scope:this});this.keymaps.parameter=new Ext.KeyMap(document,{key:Ext.EventObject.P,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("parameter")},scope:this});this.keymaps.session=new Ext.KeyMap(document,{key:Ext.EventObject.S,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("session")},scope:this});this.keymaps.trace=new Ext.KeyMap(document,
{key:Ext.EventObject.T,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("trace")},scope:this});this.keymaps.cookie=new Ext.KeyMap(document,{key:Ext.EventObject.K,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("cookie")},scope:this});this.keymaps.userdata=new Ext.KeyMap(document,{key:Ext.EventObject.U,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("userdata")},scope:this});this.keymaps.profile=new Ext.KeyMap(document,
{key:Ext.EventObject.F,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("profile")},scope:this});this.keymaps.cache=new Ext.KeyMap(document,{key:Ext.EventObject.C,ctrl:true,alt:true,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("cache")},scope:this});this.keymaps.left=new Ext.KeyMap(document,{key:Ext.EventObject.LEFT,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("left")},scope:this});this.keymaps.right=new Ext.KeyMap(document,
{key:Ext.EventObject.RIGHT,fn:function(){PXDEBUG_APP.enable&&this.viewport&&this.viewport.setActiveTab("right")},scope:this})},initApp:function(){this.bootIcon=new PXDEBUG.BootIcon;this.bootIcon.on("hidecontainer",this.hideContainer,this);this.bootIcon.on("hide",function(){this.archiveId=Ext.Phantom.archive(Ext.id(),["PXDebug-all.css"],[{id:"ExtJS_All_CSS",href:relpath+"extjs/resources/css/ext-all.css"},{id:"ExtJS_All_CSS_THEME",href:relpath+"extjs/resources/css/xtheme-gray.css"}]);Ext.DomHelper.insertFirst(Ext.getBody(),
[{id:"pxdebug-loading-mask"}]);if(!this.bootMsg)this.bootMsg=new Ext.Layer({dh:{id:"pxdebug-loading",cn:[{cls:"loading-indicator",cn:[{tag:"object",id:"pxdebuicon",classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",codebase:"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0",width:150,height:50,style:"margin-right:8px;",align:"absmiddle",cn:[{tag:"param",name:"allowScriptAccess",value:"sameDomain"},{tag:"param",name:"allowFullScreen",value:"false"},{tag:"param",
name:"movie",value:relpath+"xFrameworkPX/debug/resources/images/pxdebuicon.swf"},{tag:"param",name:"quality",value:"high"},{tag:"param",name:"bgcolor",value:"#ffffff"},{tag:"embed",src:relpath+"xFrameworkPX/debug/resources/images/pxdebuicon.swf",quality:"high",bgcolor:"#ffffff",width:150,height:50,name:"pxdebuicon",align:"middle",allowScriptAccess:"sameDomain",allowFullScreen:"false",type:"application/x-shockwave-flash",pluginspage:"http://www.macromedia.com/go/getflashplayer"}]}]}]}});var a=Ext.getBody().getViewSize();
this.bootMsg.setTop((a.height-this.bootMsg.getHeight())/2);this.bootMsg.setLeft((a.width-this.bootMsg.getWidth())/2);this.bootMsg.show();(function(){PXDEBUG_APP.showed=true;this.viewport=new PXDEBUG.Viewport;this.viewport.on("hidecontainer",this.hideContainer,this);Ext.fly("pxdebug-loading-mask").remove();this.bootMsg.remove();this.bootMsg=null;PXDEBUG_APP.enable=true;this.keymap(true)}).defer(1E3,this)},this);this.bootIcon.show()},hideContainer:function(){Ext.WindowMgr.each(function(a){a.close()},
this);this.keymap(false);this.viewport.destroy();Ext.Phantom.expand(this.archiveId);PXDEBUG_APP.enable=true;this.bootIcon.show();PXDEBUG_APP.showed=false},checkEnv:function(){if(Ext.get(document.documentElement).hasClass("pxdebug-disable"))return false;return true},keymap:function(a){Ext.iterate(this.keymaps,function(c,b){a?b.enable():b.disable()},this)},run:function(){this.commonInit();this.initApp()}});
Ext.onReady(function(){if(!window.relpath)window.relpath="";window.PXDEBUG_APP=new PXDEBUG.app.App;PXDEBUG_APP.run()});Ext.apply(Ext,{maxZindex:function(){var a=0;Ext.select("*").each(function(c){c=c.getStyle("z-index");if(Ext.isNumber(parseInt(c))&&a<c)a=c},this);return a},getScrollPos:function(){return{x:document.documentElement.scrollLeft>0?document.documentElement.scrollLeft:document.body.scrollLeft,y:document.documentElement.scrollTop>0?document.documentElement.scrollTop:document.body.scrollTop}}});
String.prototype.endsWith=function(a){var c=this.length-a.length;return c>=0&&this.lastIndexOf(a)===c};
Ext.Phantom=function(){var a={},c=[];return{archive:function(b,f,g){b=b||Ext.id();var d=Ext.DomHelper;Ext.isArray||(f=[]);Ext.fly(b)!==null&&Ext.fly(b).remove();a[b]=[];var i=d.append(Ext.getBody(),{id:b,style:"position: absolute; top: -10000px; left: -10000px; display: none"});if(Ext.isIE6){var j=Ext.getBody().dom;Ext.select("*",true,document).each(function(e){e.dom.parentNode.id===j.id&&i.id!=e.id&&i.appendChild(e.dom)},this)}else Ext.each(document.body.childNodes,function(e){if(e)(e=Ext.get(e))&&
e.dom.id!==b&&i.appendChild(e.dom)},this);Ext.select("link",true).each(function(e){var h=e.dom;h.href.toLowerCase().endsWith(".css")&&Ext.each(f,function(k){if(!h.href.endsWith(k)){a[b].push({id:h.id,href:h.href});h.parentNode.removeChild(h)}},this)},this);Ext.each(g,function(e){Ext.util.CSS.swapStyleSheet(e.id,e.href);c.push(e)},this);return b},expand:function(b){var f=Ext.get(b);if(Ext.isIE6){g=Ext.getBody().dom;Ext.select("*",true,f.dom).each(function(d){d.dom.parentNode.id===f.dom.id&&document.body.appendChild(d.dom)},
this)}else{var g=Ext.getBody().dom;Ext.select("*",true,f.dom).each(function(d){d.dom.parentNode.id===f.dom.id&&document.body.appendChild(d.dom)},this)}Ext.each(a[b],function(d){Ext.util.CSS.swapStyleSheet(d.id,d.href)},this);Ext.each(c,function(d){Ext.util.CSS.removeStyleSheet(d.id)},this)}}}();
PXDEBUG.BootIcon=Ext.extend(Ext.Component,{initComponent:function(){Ext.apply(this,{showed:false,duration:{show:0.3,hide:0.3},layer:new Ext.Layer({dh:{cls:"pxdebug-booticon",cn:[{id:"pxdebug_booticon_link",tag:"a",cls:"pxdebug-booticon-icon"}]}})});Ext.fly(window).on("scroll",function(){this.layer.setTop(Ext.getScrollPos().y)},this);this.keymap=new Ext.KeyMap(document,{key:Ext.EventObject.F9,fn:function(){if(PXDEBUG_APP.enable)this.showed?this.hide():this.fireEvent("hidecontainer",this)},scope:this});
PXDEBUG.BootIcon.superclass.initComponent.call(this)},show:function(){PXDEBUG_APP.enable=false;this.preY&&window.scrollTo(0,this.preY);this.layer.show();this.layer.setTop(Ext.getScrollPos().y);this.layer.setLeft(-50);this.layer.shift({x:0,duration:this.duration.show,easing:"easeOutStrong",opacity:1,callback:function(a){this.layer.on("click",this.hide,this);this.showed=true;PXDEBUG_APP.enable=true;this.fireEvent("show",this,a)},scope:this})},hide:function(){if(!(PXDEBUG_APP.enable===false||PXSTUDIO_APP.showed===
true)){this.preY=Ext.getScrollPos().y;PXDEBUG_APP.enable=false;this.layer.un("click",this.hide,this);this.layer.shift({x:-50,duration:this.duration.hide,easing:"easeOutStrong",opacity:0,callback:function(){this.layer.hide();this.showed=false;this.fireEvent("hide",this,this.layer)},scope:this})}}});
PXDEBUG.CacheClearWindow=Ext.extend(Ext.Window,{initComponent:function(){this.id="pxdebug_cache_clear_window";Ext.apply(this,{title:"\u30ad\u30e3\u30c3\u30b7\u30e5\u306e\u524a\u9664",iconCls:"pxdebug-icon-cacheclear",modal:true,resizable:false,autoHeight:true,defaultButton:this.id+"_btnDelete",width:300,items:[{id:this.id+"_tree",xtype:"treepanel",border:false,padding:10,useArrows:true,rootVisible:false,root:{children:[{id:"ccw_schema",text:"\u30b9\u30ad\u30fc\u30de\u30ad\u30e3\u30c3\u30b7\u30e5",
iconCls:"pxdebug-icon-none",checked:true,leaf:true},{id:"ccw_config",text:"\u8a2d\u5b9a\u30ad\u30e3\u30c3\u30b7\u30e5",iconCls:"x-hidden",checked:true,leaf:true},{id:"ccw_template",text:"\u30c6\u30f3\u30d7\u30ec\u30fc\u30c8\u30ad\u30e3\u30c3\u30b7\u30e5",iconCls:"x-hidden",checked:true,leaf:true}]}}],buttons:[{id:this.id+"_btnDelete",text:"\u4eca\u3059\u3050\u524a\u9664",handler:function(){var a=Ext.getCmp(this.id+"_tree").root;this.disable();PXDEBUG_APP.keymap(false);xFrameworkPX_DebugTools.clearCaches(a.findChild("id",
"ccw_schema").attributes.checked,a.findChild("id","ccw_config").attributes.checked,a.findChild("id","ccw_template").attributes.checked,function(){PXDEBUG_APP.keymap(true);this.close()},this)},scope:this},{text:"\u30ad\u30e3\u30f3\u30bb\u30eb",handler:function(){this.close()},scope:this}]});PXDEBUG.CacheClearWindow.superclass.initComponent.call(this)}});
PXDEBUG.HelpWindow=Ext.extend(Ext.Window,{initComponent:function(){Ext.apply(this,{title:"\u30d8\u30eb\u30d7",defaultButton:this.id+"_btnOk",iconCls:"pxdebug-icon-help",modal:true,resizable:false,autoHeight:true,width:400,items:[{border:false,height:100,style:"border-bottom: solid 1px #ccc; padding-top: 25px; padding-left: 25px; background-color: white;",html:['<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="260" height="50" id="pxdebuicon" align="middle"><param name="allowScriptAccess" value="sameDomain" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+
window.relpath+'xFrameworkPX/debug/resources/images/pxdebugversion.swf" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" /><embed src="'+window.relpath+'xFrameworkPX/debug/resources/images/pxdebugversion.swf" quality="high" bgcolor="#ffffff" width="260" height="50" name="pxdebuicon" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" /></object>']},{xtype:"grid",
border:false,store:new Ext.data.ArrayStore({autoDestroy:true,storeId:"HelpMenuStore",fields:["shortcut","description"],data:[["T","\u30c8\u30ec\u30fc\u30b9\u8868\u793a"],["P","\u30d1\u30e9\u30e1\u30fc\u30bf\u8868\u793a"],["S","\u30bb\u30c3\u30b7\u30e7\u30f3\u8868\u793a"],["K","\u30af\u30c3\u30ad\u30fc\u8868\u793a"],["U","\u30e6\u30fc\u30b6\u30fc\u30c7\u30fc\u30bf\u8868\u793a"],["Q","\u30af\u30a8\u30ea\u30fc\u8868\u793a"],["F","\u30d7\u30ed\u30d5\u30a1\u30a4\u30eb\u8868\u793a"],["Ctrl+Alt+C","\u30ad\u30e3\u30c3\u30b7\u30e5\u306e\u524a\u9664\u30a6\u30a3\u30f3\u30c9\u30a6\u8868\u793a"]]}),
colModel:new Ext.grid.ColumnModel({defaults:{sortable:false},columns:[{header:"\u30b7\u30e7\u30fc\u30c8\u30ab\u30c3\u30c8",width:150,dataIndex:"shortcut"},{header:"\u8aac\u660e",width:350,dataIndex:"description"}]}),viewConfig:{forceFit:true},listeners:{afterrender:{fn:function(){(function(){this.syncShadow()}).defer(100,this)},scope:this}},autoHeight:true,sm:new Ext.grid.RowSelectionModel({singleSelect:true})}],buttons:[{id:this.id+"_btnOk",text:"OK",handler:function(){this.close()},scope:this}]});
PXDEBUG.HelpWindow.superclass.initComponent.call(this)}});
PXDEBUG.ParameterPanel=Ext.extend(Ext.Panel,{initComponent:function(){Ext.applyIf(this,{id:Ext.id()});Ext.apply(this,{title:"\u30d1\u30e9\u30e1\u30fc\u30bf\u30fc",iconCls:"pxdebug-icon-parameter",layout:"border",items:[{region:"center",margins:"4 4 0 4",xtype:"grid",id:this.id+"_grid",store:new Ext.data.ArrayStore({autoDestroy:true,storeId:"ParameterStore",fields:["no","valiable","summary","detail","type"],data:PXDEBUG_DATA.parameter}),colModel:new Ext.grid.ColumnModel({defaults:{width:120,sortable:true},
columns:[{header:"No",width:50,dataIndex:"no"},{header:"\u7a2e\u5225",width:70,dataIndex:"type"},{header:"\u5909\u6570",dataIndex:"valiable"},{header:"\u5185\u5bb9",width:700,dataIndex:"summary"}]}),viewConfig:{},sm:new Ext.grid.RowSelectionModel({singleSelect:true})},{region:"south",margins:"0 4 4 4",split:true,id:this.id+"_detail",bodyStyle:"padding:10px;",iconCls:"pxdebug-icon-monitor-magnifier",title:"\u30d1\u30e9\u30e1\u30fc\u30bf\u30fc\u8a73\u7d30",autoScroll:true,collapsible:true,height:300}]});
PXDEBUG.ParameterPanel.superclass.initComponent.call(this)},initEvents:function(){PXDEBUG.ParameterPanel.superclass.initEvents.call(this);this.getComponent(this.id+"_grid").getSelectionModel().on("rowselect",this.onRowSelect,this)},onRowSelect:function(a,c,b){Ext.getCmp(this.id+"_detail").update(b.data.detail)}});Ext.reg("pxdebug-parameter",PXDEBUG.ParameterPanel);
PXDEBUG.ProfilerPanel=Ext.extend(Ext.Panel,{initComponent:function(){Ext.applyIf(this,{id:Ext.id()});Ext.apply(this,{title:"\u30d7\u30ed\u30d5\u30a1\u30a4\u30eb",iconCls:"pxdebug-icon-profiler",layout:"border",items:[{region:"center",margins:"4 4 4 4",xtype:"grid",id:this.id+"_grid",store:new Ext.data.ArrayStore({autoDestroy:true,storeId:"UserDataStore",fields:["no","instance","cls","method","type","time"],data:PXDEBUG_DATA.profiler}),colModel:new Ext.grid.ColumnModel({defaults:{width:120,sortable:false},
columns:[{header:"No",width:50,dataIndex:"no",renderer:function(a,c,b,f,g,d){if(d.data.items.length==b.data.no)return"";return b.data.no}},{header:"\u30a4\u30f3\u30b9\u30bf\u30f3\u30b9",width:250,dataIndex:"instance"},{header:"\u30af\u30e9\u30b9",dataIndex:"cls",width:250,renderer:function(a,c,b){if(b.data.cls==="[TOTAL]")return"";return b.data.cls}},{header:"\u30e1\u30bd\u30c3\u30c9",dataIndex:"method"},{header:"\u7a2e\u5225",dataIndex:"type"},{header:"\u30d1\u30d5\u30a9\u30fc\u30de\u30f3\u30b9",
width:700,dataIndex:"time",renderer:function(a,c,b){if(b.data.cls==="[TOTAL]"){a='<div class="pxdebug-proctime">%1$s<span>ms</span><div>';return a=a.replace("%1$s",b.data.time)}else{if(b.data.type==="User"){a='<div class="pxdebug-usertime">%1$s<span>ms</span><div>';return a=a.replace("%1$s",b.data.time)}return b.data.time}}}]}),viewConfig:{},sm:new Ext.grid.RowSelectionModel({singleSelect:true})}]});PXDEBUG.ProfilerPanel.superclass.initComponent.call(this)},initEvents:function(){PXDEBUG.ProfilerPanel.superclass.initEvents.call(this)}});
Ext.reg("pxdebug-profiler",PXDEBUG.ProfilerPanel);
PXDEBUG.QueryPanel=Ext.extend(Ext.Panel,{initComponent:function(){Ext.applyIf(this,{id:Ext.id()});Ext.apply(this,{title:"\u30af\u30a8\u30ea\u30fc",iconCls:"pxdebug-icon-query",layout:"border",items:[{region:"center",margins:"4 4 0 4",xtype:"grid",id:this.id+"_grid",store:new Ext.data.ArrayStore({autoDestroy:true,storeId:"QueryStore",fields:["no","table","module","summary","rows",{name:"time",type:"float"},"query"],data:PXDEBUG_DATA.query}),colModel:new Ext.grid.ColumnModel({defaults:{width:120,sortable:true},
columns:[{header:"No",width:50,dataIndex:"no"},{header:"\u30c6\u30fc\u30d6\u30eb",dataIndex:"table"},{header:"\u30e2\u30b8\u30e5\u30fc\u30eb",width:300,dataIndex:"module"},{header:"\u30af\u30a8\u30ea\u30fc",width:500,dataIndex:"summary"},{header:"\u53d6\u5f97\u884c\u6570",width:80,dataIndex:"rows"},{header:"\u5b9f\u884c\u6642\u9593",dataIndex:"time",renderer:function(a,c,b){a="green";c='<span style="color:%$1s;">%$2sms</span>';if(b.data.time>3)a="red";else if(b.data.time>1)a="orange";c=c.replace("%$1s",
a);return c=c.replace("%$2s",b.data.time)}}]}),viewConfig:{},sm:new Ext.grid.RowSelectionModel({singleSelect:true})},{region:"south",margins:"0 4 4 4",split:true,id:this.id+"_detail",bodyStyle:"padding:10px;",iconCls:"pxdebug-icon-database-magnifier",title:"\u30af\u30a8\u30ea\u30fc\u8a73\u7d30",autoScroll:true,collapsible:true,height:300}]});PXDEBUG.QueryPanel.superclass.initComponent.call(this)},initEvents:function(){PXDEBUG.QueryPanel.superclass.initEvents.call(this);this.getComponent(this.id+"_grid").getSelectionModel().on("rowselect",
this.onRowSelect,this)},onRowSelect:function(a,c,b){Ext.getCmp(this.id+"_detail").update(b.data.query)}});Ext.reg("pxdebug-query",PXDEBUG.QueryPanel);
PXDEBUG.TracePanel=Ext.extend(Ext.Panel,{initComponent:function(){Ext.applyIf(this,{id:Ext.id()});Ext.apply(this,{title:"\u30c8\u30ec\u30fc\u30b9",iconCls:"pxdebug-icon-trace",layout:"border",items:[{region:"center",margins:"4 4 0 4",xtype:"grid",id:this.id+"_grid",store:new Ext.data.ArrayStore({autoDestroy:true,storeId:"TraceStore",fields:["no","cls","method","line","tag","summary","detail"],data:PXDEBUG_DATA.trace}),colModel:new Ext.grid.ColumnModel({defaults:{width:120,sortable:true},columns:[{header:"No",
width:50,dataIndex:"no"},{header:"\u5185\u5bb9",width:700,dataIndex:"summary"},{header:"\u30bf\u30b0",dataIndex:"tag"},{header:"\u30af\u30e9\u30b9",dataIndex:"cls"},{header:"\u30e1\u30bd\u30c3\u30c9",dataIndex:"method"},{header:"\u30e9\u30a4\u30f3",dataIndex:"line"}]}),viewConfig:{},sm:new Ext.grid.RowSelectionModel({singleSelect:true})},{region:"south",margins:"0 4 4 4",split:true,id:this.id+"_detail",bodyStyle:"padding:10px;",iconCls:"pxdebug-icon-flag-green-magnifier",title:"\u30c8\u30ec\u30fc\u30b9\u8a73\u7d30",
autoScroll:true,collapsible:true,height:300}]});PXDEBUG.TracePanel.superclass.initComponent.call(this)},initEvents:function(){PXDEBUG.TracePanel.superclass.initEvents.call(this);this.getComponent(this.id+"_grid").getSelectionModel().on("rowselect",this.onRowSelect,this)},onRowSelect:function(a,c,b){Ext.getCmp(this.id+"_detail").update(b.data.detail)}});Ext.reg("pxdebug-trace",PXDEBUG.TracePanel);
PXDEBUG.UserDataPanel=Ext.extend(Ext.Panel,{initComponent:function(){Ext.applyIf(this,{id:Ext.id()});Ext.apply(this,{title:"\u30e6\u30fc\u30b6\u30fc\u30c7\u30fc\u30bf",iconCls:"pxdebug-icon-userdata",layout:"border",items:[{region:"center",margins:"4 4 0 4",xtype:"grid",id:this.id+"_grid",store:new Ext.data.ArrayStore({autoDestroy:true,storeId:"UserDataStore",fields:["no","valiable","summary","detail"],data:PXDEBUG_DATA.userdata}),colModel:new Ext.grid.ColumnModel({defaults:{width:120,sortable:true},
columns:[{header:"No",width:50,dataIndex:"no"},{header:"\u30a2\u30b5\u30a4\u30f3\u5909\u6570",dataIndex:"valiable"},{header:"\u5185\u5bb9",width:700,dataIndex:"summary"}]}),viewConfig:{},sm:new Ext.grid.RowSelectionModel({singleSelect:true})},{region:"south",margins:"0 4 4 4",split:true,id:this.id+"_detail",bodyStyle:"padding:10px;",iconCls:"pxdebug-icon-note-magnifier",title:"\u30e6\u30fc\u30b6\u30fc\u30c7\u30fc\u30bf\u8a73\u7d30",autoScroll:true,collapsible:true,height:300}]});PXDEBUG.UserDataPanel.superclass.initComponent.call(this)},
initEvents:function(){PXDEBUG.UserDataPanel.superclass.initEvents.call(this);this.getComponent(this.id+"_grid").getSelectionModel().on("rowselect",this.onRowSelect,this)},onRowSelect:function(a,c,b){Ext.getCmp(this.id+"_detail").update(b.data.detail)}});Ext.reg("pxdebug-userdata",PXDEBUG.UserDataPanel);
PXDEBUG.SessionPanel=Ext.extend(Ext.Panel,{initComponent:function(){Ext.applyIf(this,{id:Ext.id()});Ext.apply(this,{title:"\u30bb\u30c3\u30b7\u30e7\u30f3",iconCls:"pxdebug-icon-session",layout:"border",items:[{tbar:[{id:this.id+"_btnDelete",text:"\u524a\u9664",disabled:true,iconCls:"pxdebug-icon-session-delete",handler:function(){var a=Ext.getCmp(this.id+"_grid"),c=a.getSelectionModel();Ext.MessageBox.confirm("\u78ba\u8a8d",c.getSelected().data.key+"\u3092\u524a\u9664\u3057\u307e\u3059\u304b\uff1f",
function(b){if(b=="yes"){Ext.MessageBox.show({title:"\u30bb\u30c3\u30b7\u30e7\u30f3\u524a\u9664",msg:"\u524a\u9664\u4e2d...",width:200,buttons:false,closable:false,wait:true,modal:true,minWidth:this.minProgressWidth,waitConfig:{}});xFrameworkPX_DebugTools.removeSession(c.getSelected().data.key,function(){a.store.remove(c.getSelected());Ext.getCmp(this.id+"_detail").update("");a.store.getCount()==0&&Ext.getCmp(this.id+"_btnDelete").disable();Ext.MessageBox.hide()},this)}},this)},scope:this}],region:"center",
margins:"4 4 0 4",xtype:"grid",id:this.id+"_grid",store:new Ext.data.ArrayStore({autoDestroy:true,storeId:"SessionStore",fields:["no","key","detail","summary"],data:PXDEBUG_DATA.session}),colModel:new Ext.grid.ColumnModel({defaults:{width:120,sortable:true},columns:[{header:"No",width:50,dataIndex:"no"},{header:"\u5909\u6570",dataIndex:"key"},{header:"\u5185\u5bb9",width:700,dataIndex:"summary"}]}),viewConfig:{},sm:new Ext.grid.RowSelectionModel({singleSelect:true,listeners:{rowselect:{fn:function(){Ext.getCmp(this.id+
"_btnDelete").enable()},scope:this},rowdeselect:{fn:function(){Ext.getCmp(this.id+"_btnDelete").disable()},scope:this}}})},{region:"south",margins:"0 4 4 4",split:true,id:this.id+"_detail",bodyStyle:"padding:10px;",iconCls:"pxdebug-icon-flag-bricks-magnifier",title:"\u30bb\u30c3\u30b7\u30e7\u30f3\u8a73\u7d30",autoScroll:true,collapsible:true,height:300}]});PXDEBUG.SessionPanel.superclass.initComponent.call(this)},initEvents:function(){PXDEBUG.SessionPanel.superclass.initEvents.call(this);this.getComponent(this.id+
"_grid").getSelectionModel().on("rowselect",this.onRowSelect,this)},onRowSelect:function(a,c,b){Ext.getCmp(this.id+"_detail").update(b.data.detail)}});Ext.reg("pxdebug-session",PXDEBUG.SessionPanel);
PXDEBUG.CookiePanel=Ext.extend(Ext.Panel,{initComponent:function(){Ext.applyIf(this,{id:Ext.id()});Ext.apply(this,{title:"\u30af\u30c3\u30ad\u30fc",iconCls:"pxdebug-icon-cookie",layout:"border",items:[{tbar:[{id:this.id+"_btnDelete",text:"\u524a\u9664",disabled:true,iconCls:"pxdebug-icon-cookie-delete",handler:function(){var a=Ext.getCmp(this.id+"_grid"),c=a.getSelectionModel();Ext.MessageBox.confirm("\u78ba\u8a8d",c.getSelected().data.key+"\u3092\u524a\u9664\u3057\u307e\u3059\u304b\uff1f",function(b){if(b==
"yes"){b=new Date;b.setTime(b.getTime()+-86400000);b=b.toGMTString();document.cookie=c.getSelected().data.key+"="+escape(0)+";expires="+b;a.store.remove(c.getSelected());Ext.getCmp(this.id+"_detail").update("");a.store.getCount()==0&&Ext.getCmp(this.id+"_btnDelete").disable()}},this)},scope:this}],region:"center",margins:"4 4 0 4",xtype:"grid",id:this.id+"_grid",store:new Ext.data.ArrayStore({autoDestroy:true,storeId:"CookieStore",fields:["no","key","detail","summary"],data:PXDEBUG_DATA.cookie}),
colModel:new Ext.grid.ColumnModel({defaults:{width:120,sortable:true},columns:[{header:"No",width:50,dataIndex:"no"},{header:"\u5909\u6570",dataIndex:"key"},{header:"\u5185\u5bb9",width:700,dataIndex:"summary"}]}),viewConfig:{},sm:new Ext.grid.RowSelectionModel({singleSelect:true,listeners:{rowselect:{fn:function(){Ext.getCmp(this.id+"_btnDelete").enable()},scope:this},rowdeselect:{fn:function(){Ext.getCmp(this.id+"_btnDelete").disable()},scope:this}}})},{region:"south",margins:"0 4 4 4",split:true,
id:this.id+"_detail",bodyStyle:"padding:10px;",iconCls:"pxdebug-icon-flag-asterisk-yellow-magnifier",title:"\u30af\u30c3\u30ad\u30fc\u8a73\u7d30",autoScroll:true,collapsible:true,height:300}]});PXDEBUG.CookiePanel.superclass.initComponent.call(this)},initEvents:function(){PXDEBUG.CookiePanel.superclass.initEvents.call(this);this.getComponent(this.id+"_grid").getSelectionModel().on("rowselect",this.onRowSelect,this)},onRowSelect:function(a,c,b){Ext.getCmp(this.id+"_detail").update(b.data.detail)}});
Ext.reg("pxdebug-cookie",PXDEBUG.CookiePanel);
PXDEBUG.Viewport=Ext.extend(Ext.Viewport,{initComponent:function(){Ext.apply(this,{id:Ext.id()});Ext.apply(this,{layout:"fit",items:[{title:"xFrameworkPX Debug Tools",iconCls:"pxdebug-icon-logo",layout:"border",tools:[{id:"gear",handler:function(){(new PXDEBUG.CacheClearWindow).show()},scope:this},{id:"help",handler:function(){(new PXDEBUG.HelpWindow).show()},scope:this},{id:"close",handler:function(){this.fireEvent("hidecontainer")},scope:this}],border:false,items:[{xtype:"tabpanel",id:this.id+"_tab",
deferredRender:false,activeItem:0,border:false,listeners:{tabchange:{fn:function(a,c){var b=Ext.getCmp(c.id+"_grid"),f=b.getSelectionModel();b.store.getCount()>0&&function(){b.getView().focusEl.focus();f.selectFirstRow()}.defer(100,this);Ext.iterate(a.items.items,function(g,d){if(g==c)Ext.getCmp(this.id+"_tab").activeTabPos=d},this)},scope:this},afterrender:{fn:function(){Ext.getCmp(this.id+"_tab").activeTabPos=0},scope:this}},region:"center",items:[{xtype:"pxdebug-trace",id:this.id+"_trace"},{xtype:"pxdebug-parameter",
id:this.id+"_parameter"},{xtype:"pxdebug-session",id:this.id+"_session"},{xtype:"pxdebug-cookie",id:this.id+"_cookie"},{xtype:"pxdebug-userdata",id:this.id+"_userdata"},{xtype:"pxdebug-query",id:this.id+"_query"},{xtype:"pxdebug-profiler",id:this.id+"_profiler"}]}]}]});PXDEBUG.Viewport.superclass.initComponent.call(this)},getTab:function(){return Ext.getCmp(this.id+"_tab")},setActiveTab:function(a){switch(a){case "query":this.getTab().setActiveTab(5);break;case "profile":this.getTab().setActiveTab(6);
break;case "session":this.getTab().setActiveTab(2);break;case "cookie":this.getTab().setActiveTab(3);break;case "userdata":this.getTab().setActiveTab(4);break;case "parameter":this.getTab().setActiveTab(1);break;case "trace":this.getTab().setActiveTab(0);break;case "cache":(new PXDEBUG.CacheClearWindow).show();break;case "left":a=this.getTab();var c=--a.activeTabPos;if(c<0){c=a.items.items.length-1;a.activeTabPos=c}a.setActiveTab(c);break;case "right":a=this.getTab();c=++a.activeTabPos;if(c>=a.items.items.length){c=
0;a.activeTabPos=0}a.setActiveTab(c);break}}});
