if(!window.console)window.console={log:Ext.emptyFn,dir:Ext.emptyFn,debug:Ext.emptyFn,info:Ext.emptyFn,warn:Ext.emptyFn,error:Ext.emptyFn,time:Ext.emptyFn,timeEnd:Ext.emptyFn,pforile:Ext.emptyFn,pfofileEnd:Ext.emptyFn,trace:Ext.emptyFn,group:Ext.emptyFn,groupEnd:Ext.emptyFn,dirxml:Ext.emptyFn};Ext.ns("PXSTUDIO","PXSTUDIO.app","PXSTUDIO.grid","PXSTUDIO.form","PXSTUDIO.tree");
PXSTUDIO.app.App=Ext.extend(Ext.util.Observable,{commonInit:function(){Ext.apply(this,{appName:"xFrameworkPX Studio Express",version:"1.0.0a",showed:false,enable:false});Ext.BLANK_IMAGE_URL=relpath+"extjs/resources/images/default/s.gif";Ext.QuickTips.init();Ext.Direct.addProvider(PXSTUDIO.app.REMOTING_API);var a=Ext.maxZindex();if(Ext.WindowMgr.zseed<a)Ext.WindowMgr.zseed=a},initApp:function(){this.keymap=new Ext.KeyMap(document,{key:Ext.EventObject.F8,fn:function(){if(PXSTUDIO_APP.enable&&PXDEBUG_APP.showed!==
true){PXSTUDIO_APP.enable=false;this.fireEvent("showcontainer",this.showed)}},scope:this});this.on("showcontainer",function(a){if(a)this.hideContainer();else{this.archiveId=Ext.Phantom.archive(Ext.id(),["PXStudio-all.css"],[{id:"ExtJS_All_CSS",href:relpath+"extjs/resources/css/ext-all.css"},{id:"ExtJS_All_CSS_THEME",href:relpath+"extjs/resources/css/xtheme-gray.css"}]);Ext.DomHelper.insertFirst(Ext.getBody(),[{id:"pxstudio-loading-mask"}]);if(!this.bootMsg)this.bootMsg=new Ext.Layer({dh:{id:"pxdebug-loading",
cn:[{cls:"loading-indicator",cn:[{tag:"object",id:"pxdebuicon",classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",codebase:"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0",width:150,height:50,style:"margin-right:8px;",align:"absmiddle",cn:[{tag:"param",name:"allowScriptAccess",value:"sameDomain"},{tag:"param",name:"allowFullScreen",value:"false"},{tag:"param",name:"movie",value:relpath+"xFrameworkPX/studio/resources/images/pxstudioicon.swf"},{tag:"param",name:"quality",
value:"high"},{tag:"param",name:"bgcolor",value:"#ffffff"},{tag:"embed",src:relpath+"xFrameworkPX/studio/resources/images/pxstudioicon.swf",quality:"high",bgcolor:"#ffffff",width:150,height:50,name:"pxdebuicon",align:"middle",allowScriptAccess:"sameDomain",allowFullScreen:"false",type:"application/x-shockwave-flash",pluginspage:"http://www.macromedia.com/go/getflashplayer"}]}]}]}});a=Ext.getBody().getViewSize();this.bootMsg.setTop((a.height-this.bootMsg.getHeight())/2);this.bootMsg.setLeft((a.width-
this.bootMsg.getWidth())/2);this.bootMsg.show();(function(){PXSTUDIO_APP.showed=true;this.viewport=new PXSTUDIO.Viewport;this.viewport.on("hidecontainer",this.hideContainer,this);Ext.fly("pxstudio-loading-mask").remove();this.bootMsg.remove();this.bootMsg=null;PXSTUDIO_APP.enable=true}).defer(1E3,this)}},this);PXSTUDIO_APP.enable=true},hideContainer:function(){Ext.Phantom.expand(this.archiveId);this.viewport.destroy();PXSTUDIO_APP.enable=true;PXSTUDIO_APP.showed=false},run:function(){this.commonInit();
this.initApp()}});Ext.onReady(function(){if(!window.relpath)window.relpath="";window.PXSTUDIO_APP=new PXSTUDIO.app.App;PXSTUDIO_APP.run()});
Ext.apply(Ext,{maxZindex:function(){var a=0;Ext.select("*").each(function(e){e=e.getStyle("z-index");if(Ext.isNumber(parseInt(e))&&a<e)a=e},this);return a},getScrollPos:function(){return{x:document.documentElement.scrollLeft>0?document.documentElement.scrollLeft:document.body.scrollLeft,y:document.documentElement.scrollTop>0?document.documentElement.scrollTop:document.body.scrollTop}}});String.prototype.endsWith=function(a){var e=this.length-a.length;return e>=0&&this.lastIndexOf(a)===e};
Ext.Phantom=function(){var a={},e=[];return{archive:function(c,f,h){c=c||Ext.id();var d=Ext.DomHelper;Ext.isArray||(f=[]);Ext.fly(c)!==null&&Ext.fly(c).remove();a[c]=[];var i=d.append(Ext.getBody(),{id:c,style:"position: absolute; top: -10000px; left: -10000px; display: none"});if(Ext.isIE6){var j=Ext.getBody().dom;Ext.select("*",true,document).each(function(b){b.dom.parentNode.id===j.id&&i.id!=b.id&&i.appendChild(b.dom)},this)}else Ext.each(document.body.childNodes,function(b){if(b)(b=Ext.get(b))&&
b.dom.id!==c&&i.appendChild(b.dom)},this);Ext.select("link",true).each(function(b){var g=b.dom;g.href.toLowerCase().endsWith(".css")&&Ext.each(f,function(k){if(!g.href.endsWith(k)){a[c].push({id:g.id,href:g.href});g.parentNode.removeChild(g)}},this)},this);Ext.each(h,function(b){Ext.util.CSS.swapStyleSheet(b.id,b.href);e.push(b)},this);return c},expand:function(c){var f=Ext.get(c);if(Ext.isIE6){h=Ext.getBody().dom;Ext.select("*",true,f.dom).each(function(d){d.dom.parentNode.id===f.dom.id&&document.body.appendChild(d.dom)},
this)}else{var h=Ext.getBody().dom;Ext.select("*",true,f.dom).each(function(d){d.dom.parentNode.id===f.dom.id&&document.body.appendChild(d.dom)},this)}Ext.each(a[c],function(d){Ext.util.CSS.swapStyleSheet(d.id,d.href)},this);Ext.each(e,function(d){Ext.util.CSS.removeStyleSheet(d.id)},this)}}}();
PXSTUDIO.Viewport=Ext.extend(Ext.Viewport,{initComponent:function(){Ext.apply(this,{id:Ext.id()});Ext.apply(this,{layout:"fit",items:[{title:PXSTUDIO_APP.appName,iconCls:"pxstudio-icon-logo",layout:"border",tools:[{id:"gear",handler:function(){},scope:this},{id:"help",handler:function(){},scope:this},{id:"close",handler:function(){this.fireEvent("hidecontainer")},scope:this}],border:false,items:[{region:"center",title:"\u3081\u3044\u3093"}]}]});PXSTUDIO.Viewport.superclass.initComponent.call(this)}});
